# Generated by Django 3.2.5 on 2021-07-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='dascount',
            new_name='discount',
        ),
    ]
